# Makefile variables
#
# Project name
PROJECT 	:= "pyproject-template"
# Python environment manager
VENV 		:= .venv
# Python environment Python interpreter
PYTHON 		:= $(VENV)/bin/python
# Python enviroment installer
PIP 		:= $(VENV)/bin/pip

.PHONY: $(PYTHON) $(PIP) install run run_help test clean

# Build Python environment using system Python
$(PYTHON):
	python3 -m venv $(VENV)

# Install and upgrade pip in the Python environment
$(PIP): $(PYTHON)
	$(PYTHON) -m pip install -U pip

# Install the project in editable mode (this means you
# can edit Python package source code and execute the 
# package without re-installing)
#
# Pip install looks in pyproject.toml for metadata
# on packaging
install: | $(PIP)
	$(PIP) install -e ".[dev]"

run:
	@echo "Execute main entry point"
	$(VENV)/bin/$(PROJECT) logfile1 patternfile1 outputfile1

run_help:
	@echo "Execute main entry point with help flag"
	$(VENV)/bin/$(PROJECT) -h

test:
	@echo "Running unit tests"
	$(PYTHON) -m unittest discover -s tests

# Removes all directories and files generated by install including logs
clean:
	rm -rf $(VENV)
	find . -type d -name '__pycache__' -prune -exec rm -rf {} +
	rm -rf src/*.egg-info
