# Build system backend dependency (Python packaging and build library)
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# Define project meta data here
[project]
name = "pyproject-template"
version = "0.0.1"
requires-python = ">=3.11"

# Add the project Python dependencies here
dependencies = [
    "datetime",
    "argparse"
]

#[tool.setuptools.packages]
#find = {} # Scan the project directory with the default parameters

# Add directory containing packages here
# For example
# Where "src"
# Include "*" (All)
# Exclude [] (None)
[tool.setuptools.packages.find]
where = ["src"]     # ["."] by default
include = ["*"]     # ["*"] is default
exclude = []        # empty by default
namespaces = true   # true by default

# Add entry point function(s)
[project.scripts]
pyproject-template = "pyproject_template.main:main"
